## RUN ONCE

In [25]:
!git clone https://github.com/magicleap/SuperGluePretrainedNetwork.git

fatal: destination path 'SuperGluePretrainedNetwork' already exists and is not an empty directory.


In [4]:
!pip install torch torchvision numpy opencv-python
!cd SuperGluePretrainedNetwork && pip install -r requirements.txt


ERROR: Ignored the following yanked versions: 3.4.11.39, 3.4.17.61, 4.4.0.42, 4.4.0.44, 4.5.4.58, 4.5.5.62, 4.7.0.68
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.60, 4.5.5.64, 4.6.0.66, 4.7.0.72, 4.8.0.74, 4.8.0.76, 4.8.1.78, 4.9.0.80, 4.10.0.82, 4.10.0.84, 4.11.0.86)
ERROR: No matching distribution found for opencv-python==4.1.2.30


## Setup

In [1]:
import sys
import os

# Add the models directory to Python path
sys.path.append(os.path.abspath("SuperGluePretrainedNetwork"))

# Now import the models
from models.superpoint import SuperPoint
from models.superglue import SuperGlue

In [2]:
%run GroundTruthGenerator.py

## Main Running Section

## Debugging/Test Cases

In [ ]:
# Cell: Test with two image pairs using the updated folder structure

import os

# Define the test data and output directories
dataset_dir = "test_data"           # Root folder containing "rgb" and "thermal"
test_output_dir = "test_output"   # Folder for ground truth files

# Ensure output directory exists
os.makedirs(test_output_dir, exist_ok=True)

# Define the pair IDs corresponding to your images (filenames without extension)
pair_ids = ["IM_00006", "IM_04490"]

# Instantiate the GroundTruthGenerator (ensure your module is updated to use the new ImageLoader)
gt_generator = GroundTruthGenerator(dataset_dir, test_output_dir, debug=True)

# Override the get_all_pair_ids method to return the two specific image pairs
gt_generator.get_all_pair_ids = lambda debug=False: pair_ids

# Run the generator workflow for both image pairs.
gt_generator.run(debug=True)


/Users/batuhan/Documents/tedü/4th year/final/vis_mis/Create_Ground_Truth_data/SuperGluePretrainedNetwork/models/superpoint.py:137: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur

Loaded SuperPoint model


/Users/batuhan/Documents/tedü/4th year/final/vis_mis/Create_Ground_Truth_data/SuperGluePretrainedNetwork/models/superglue.py:226: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature

Loaded SuperGlue model ("indoor" weights)
[GroundTruthGenerator] Models loaded on cpu
[DEBUG] Initializing GroundTruthGenerator with data_dir: test_data and backend_dir: test_output
Loaded SuperPoint model
Loaded SuperGlue model ("indoor" weights)
[DEBUG] Starting main processing loop...
[DEBUG] Processing next image pair: IM_00006
[DEBUG] Starting processing for image pair: IM_00006
[DEBUG] Loaded images for pair IM_00006: RGB image: [[[202 210 212]
  [213 221 223]
  [ 96 105 107]
  ...
  [197 209 209]
  [197 209 209]
  [197 209 209]]

 [[ 44  49  55]
  [ 59  62  69]
  [ 62  65  74]
  ...
  [197 209 209]
  [195 207 207]
  [198 210 210]]

 [[ 54  57  66]
  [ 52  55  64]
  [110 113 122]
  ...
  [198 210 210]
  [198 210 210]
  [198 210 210]]

 ...

 [[120 123 114]
  [111 114 105]
  [113 116 107]
  ...
  [133 129 118]
  [134 130 119]
  [129 125 114]]

 [[108 110  99]
  [114 117 108]
  [119 122 113]
  ...
  [130 126 115]
  [127 123 112]
  [128 124 113]]

 [[123 125 114]
  [122 124 113]
  [

2025-03-19 14:13:52.667 Python[75183:12249649] +[IMKClient subclass]: chose IMKClient_Modern
2025-03-19 14:13:52.667 Python[75183:12249649] +[IMKInputSession subclass]: chose IMKInputSession_Modern


[DEBUG] User approved 1 matches.
[DEBUG] Ground truth file written for pair: IM_00006
[DEBUG] Processing next image pair: IM_04490
[DEBUG] Starting processing for image pair: IM_04490
[DEBUG] Loaded images for pair IM_04490: RGB image: [[[195 211 211]
  [195 211 211]
  [194 210 210]
  ...
  [152 158 182]
  [153 164 192]
  [123 137 166]]

 [[195 211 211]
  [196 212 212]
  [194 210 210]
  ...
  [144 150 174]
  [128 139 167]
  [131 145 174]]

 [[195 211 211]
  [196 212 212]
  [194 210 210]
  ...
  [118 126 149]
  [120 134 161]
  [129 142 174]]

 ...

 [[ 62  67  73]
  [ 68  73  79]
  [ 68  73  79]
  ...
  [ 49  54  58]
  [ 50  55  59]
  [ 46  54  57]]

 [[ 66  71  77]
  [ 67  72  78]
  [ 70  75  81]
  ...
  [ 53  56  61]
  [ 48  56  59]
  [ 49  59  61]]

 [[ 69  74  80]
  [ 72  77  83]
  [ 69  74  80]
  ...
  [ 52  60  63]
  [ 48  56  59]
  [ 46  56  58]]], Thermal image: [[[  5   5   5]
  [  1   1   1]
  [  1   1   1]
  ...
  [110 110 110]
  [107 107 107]
  [121 121 121]]

 [[  0   0   0

TclError: image "pyimage3" doesn't exist

: 